--- Virtualmaster public API---
---
# Structure of resources
## Infrastructure
Available at URL: https://infra.virtualmaster.com/api/v1/

Resouces:

- Virtual
- Ip Address
- Hostnode
- Cluster
- Network interface
- Migration
- Request
- Setting
- Subnet
- Violation
- Volume group
- Logical volume
- Replication

## Billing
Available at URL: https://billing.virtualmaster.com/api/v1/

Resources:

- Customer
- Service Instance
- Invoice
- Service Invoice Item
- Grouped Consumed Resources

## Support
Available at URL: https://support.virtualmaster.com/api/v1/

Resources:

- Issue
- Issue Item
- Tracked Time

## Imagestore
Available at URL: https://imagestore.virtualmaster.com/api/v1/

Resources:

- Image
- Operating System

## Backup
Available at URL: https://backup.virtualmaster.com/api/v1/

Resources:

- Repository
- Backup


## ID - OAuth provider
Available at URL: https://id.virtualmaster.com/api/v1/

Resources:

- Person
- Email
- Phone Number
- SSH Key
- Authorized Backend

---

-- Customers --

Creates new customer

Request attributes: 

  - email: Company's billing email contact
  - legal_name: Official, full name of company
  - street: Official address street name
  - number: Official address building number
  - address2: Additional address line
  - city: Official address city
  - zip: Postal code
  - country: country code ISO 3166-1 alpha-2
  - invoice_name: Name of representative of company able to reecive billing documents
  - ic: Company identification number
  - vat: TAX number (VAT number) without country prefix
  - vat_prefix: TAX number country prefix
  - locale: ISO 639-1 code of language used in all documents and official communication
  
POST   /customers
> Accept: application/json
{
  "email": "ak@vmin.cz",
  "legal_name": "ACME ltd",
  "street": "Mulholand Drive",
  "number": "13",
  "address2": "Upthehill quarter",
  "city": "Cernosice",
  "invoice_name": "Oh Mc'Donald",
  "zip": "25228",
  "ic": "12345678",
  "vat": "12345678",
  "country": "CZ",
  "paying_vat": "true",
  "vat_prefix": "CZ",
  "locale": "cs"
}
< 201
< Content-Type: application/json
{
  "email": "ak@vmin.cz",
  "legal_name": "ACME ltd",
  "street": "Mulholand Drive",
  "number": "13",
  "address2": "Upthehill quarter",
  "city": "Cernosice",
  "invoice_name": "Oh Mc'Donald",
  "zip": "25228",
  "ic": "12345678",
  "vat": "12345678",
  "country": "CZ",
  "paying_vat": "true",
  "vat_prefix": "CZ",
  "locale": "cs",
  "id": 1
}


Get list of all customers
GET /customers
> Accept: application/json
< 200
< Content-Type: application/json
[
  {
    "email": "ak@vmin.cz",
    "legal_name": "ACME ltd",
    "street": "Mulholand Drive",
    "number": "13",
    "address2": "Upthehill quarter",
    "city": "Cernosice",
    "invoice_name": "Oh Mc'Donald",
    "zip": "25228",
    "ic": "12345678",
    "vat": "12345678",
    "country": "CZ",
    "paying_vat": "true",
    "vat_prefix": "CZ",
    "locale": "cs",
    "id": 1
  }
]


Get detail of specific customer
GET    /customers/1
> Accept: application/json
< 200
< Content-Type: application/json
{
  "email": "ak@vmin.cz",
  "legal_name": "ACME ltd",
  "street": "Mulholand Drive",
  "number": "13",
  "address2": "Upthehill quarter",
  "city": "Cernosice",
  "invoice_name": "Oh Mc'Donald",
  "zip": "25228",
  "ic": "12345678",
  "vat": "12345678",
  "country": "CZ",
  "paying_vat": "true",
  "vat_prefix": "CZ",
  "locale": "cs",
  "id": 1
}


Update specific customer
PUT    /customers/1
> Accept: application/json
{
  "email": "adam.kliment@virtualmaster.cz",
  "legal_name": "Virtualmaster",
}
< 204


Delete specific customer
DELETE    /customers/1
> Accept: application/json
< 204


-- Service instances --

Create service instance

Only admin can do this

Attributes:

- identificator: unique identificator for the service instance, if not present, will be generated
- price: unit price without tax
- currency: currency (can't differ from customer at the moment)
- service_attributes: JSON with serialized service attribtues

POST /customers/1/service_instances
> Accept: application/json
{
    "identificator": "virtual-1",
    "price": "1.5",
    "currency": "CZK",
    "service_attributes": {
        "volume": "3"
    }
}
< 201
< Content-Type: application/json
{
    "id": "1",
    "identificator": "virtual-1",
    "price": "1.5",
    "currency": "CZK",
    "service_attributes": {
        "volume": "3"
    },
    "version": "1"
}

Get all existing service instances for the customer

GET /customers/1/service_instances
> Accept: application/json
< 200
< Content-Type: application/json
[
{
    "id": "1",
    "identificator": "virtual-1",
    "price": "1.5",
    "currency": "CZK",
    "service_attributes": {
        "volume": "3"
    },
    "version": "1"
}
]

Get detail of existing service instance

GET /customers/1/service_instances/1
> Accept: application/json
< 200
< Content-Type: application/json
{
    "id": "1",
    "identificator": "virtual-1",
    "price": "1.5",
    "currency": "CZK",
    "service_attributes": {
        "volume": "3"
    },
    "version": "1"
}


Update existing service instance

PUT /customers/1/service_instances/1
> Accept: application/json
{
    "price": "2",
    "service_attributes": {
        "volume": "4"
    }
}
< 204


Delete existing service instance

DELETE /customers/1/service_instances/1
> Accept: application/json
< 204


-- Service invoice items --

Create new, not invoiced (opened) service invoice item for customer

Attributes:

  - desc: Item description
  - quantity: invoiced units queantity
  - unitprice: price for 1 invoiced unit without tax
  - discount: discount in percents
  - tax: tax in percents
  - note: Item note
  - code: Code for type of transaction
  - started_at: start of fullfillment in format ISO 8601
  - ended_at: end of fullfillment in format ISO 8601

POST /customers/1/service_invoice_items
> Accept: application/json
{
    "desc": "Item description",
    "quantity": "10",
    "unitprice": "1",
    "discount": "0",
    "tax": "20",
    "note": "Item note",
    "code": "service",
    "started_at" "2012-08-1T00:01:01+02:00",
    "ended_at":  "2012-08-1T00:11:01+02:00",
}
< 201
< Content-Type: application/json
{
    "id": "1",
    "desc": "Item description",
    "quantity": "10",
    "unitprice": "1",
    "discount": "0",
    "tax": "20",
    "note": "Item note",
    "code": "service",
    "started_at" "2012-08-1T00:01:01+02:00",
    "ended_at":  "2012-08-1T00:11:01+02:00",
}



Get all customer's invoice items
GET /customers/1/service_invoice_items
> Accept: application/json
< 200
< Content-Type: application/json
[
{
    "id": "1",
    "desc": "Item description",
    "quantity": "10",
    "unitprice": "1",
    "discount": "0",
    "tax": "20",
    "note": "Item note",
    "code": "service",
    "started_at" "2012-08-1T00:01:01+02:00",
    "ended_at":  "2012-08-1T00:11:01+02:00",
}
]


Get specific invoice item
GET /customers/1/service_invoice_items/1
> Accept: application/json
< 200
< Content-Type: application/json
{
    "id": "1",
    "desc": "Item description",
    "quantity": "10",
    "unitprice": "1",
    "discount": "0",
    "tax": "20",
    "note": "Item note",
    "code": "service",
    "started_at" "2012-08-1T00:01:01+02:00",
    "ended_at":  "2012-08-1T00:11:01+02:00",
}


Update specifc invoice item
PUT /customers/1/service_invoice_items/1
> Accept: application/json
{
  "desc" "Changed item description"    
}
< 204


Delete specifc invoice item
DELETE /customers/1/service_invoice_items/1
> Accept: application/json
< 204


-- Invoices --

Get all customer's existing invoices

GET /customers/1/invoices
> Accept: application/json
< 200
< Content-Type: application/json
[
{
    "customer_id": "1",
    "number": "2012010001",
    "issued_at": "2012-01-01",
    "due_at": "2012-01-15",
    "fulfillment_at": "2011-12-31",
    "issued_by": "TinTin MacGyver",
    "payment_type": "bank_transfer",
    "rounding": "0",
    "state": "paid",
    "type": "ServiceInvoice",
    "tax_rate": "20",
    "price_total": "2200",
    "language": "cs",
    "vs": "2012010001",
    "currency": "CZK",
    "tax_mode": "czech"
},
{
    "customer_id": "1",
    "number": "2012010001",
    "issued_at": "2012-01-01",
    "due_at": "2012-01-15",
    "fulfillment_at": "2011-12-31",
    "issued_by": "TinTin MacGyver",
    "payment_type": "bank_transfer",
    "rounding": "0",
    "state": "paid",
    "type": "CreditInvoice",
    "tax_rate": "20",
    "price_total": "5000",
    "language": "cs",
    "vs": "2012010001",
    "currency": "CZK",
    "tax_mode": "czech"
}
]


Get detail of specific customer's 

GET /customers/1/invoices/2012010001
> Accept: application/json
< 200
< Content-Type: application/json
{
    "customer_id": "1",
    "number": "2012010001",
    "issued_at": "2012-01-01",
    "due_at": "2012-01-15",
    "fulfillment_at": "2011-12-31",
    "issued_by": "TinTin MacGyver",
    "payment_type": "bank_transfer",
    "rounding": "0",
    "state": "paid",
    "type": "ServiceInvoice",
    "tax_rate": "20",
    "price_total": "2200",
    "language": "cs",
    "vs": "2012010001",
    "currency": "CZK",
    "tax_mode": "czech"
}


Download specific customer's invoice in PDF
Test comment for apiary

GET /customers/1/invoices/2012010001.pdf
< 200
< Content-Type:application/pdf




-- Authorized Backend --
Retreive all authorized backends for person
GET   /persons/1/authorized_backends
> Accept: application/json
< 201
< Content-Type: application/json
{
  "authorized_backends": [
    {
      "authorized_backend": {
        "id": "1",
        "backend_type": "Support",
        "person_id": "1",
        "url": "http://virtualmaster.apiary.io",
        "credentials": {
          "username": "netmilk",
          "password": "1234"
        }
      }
    },
    {
      "authorized_backend": {
        "id": "1",
        "backend_type": "Billing",
        "person_id": "1",
        "url": "http://virtualmaster.apiary.io",
        "credentials": {
          "username": "netmilk",
          "password": "1234"
        }
      }
    },
    {
      "authorized_backend": {
        "id": "1",
        "backend_type": "Infrastructure",
        "person_id": "1",
        "url": "http://virtualmaster.apiary.io",
        "credentials": {
          "username": "netmilk",
          "password": "1234"
        }
      }
    },
    {
      "authorized_backend": {
        "id": "1",
        "backend_type": "Id",
        "person_id": "1",
        "url": "http://virtualmaster.apiary.io",
        "credentials": {
          "username": "netmilk",
          "password": "1234"
        }
      }
    }
  ]
}





-- Cluster --
GET   /clusters/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "cluster": {
    "tenant_id": 1,
    "name": "Virtualaster Prague - locality 1",
    "realm_name": "vm-prague-1",
    "public": "true",
    "id": 1
  }
}


-- Hostnode --
GET   /hostnodes/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "hostnode": {
    "hostname": "node1.vmin.cz",
    "private_ip_id": 1,
    "public_ip_id": 2,
    "ram": 8096,
    "cores": 8,
    "comment": "Probably faulty memory",
    "tenant_id": 1,
    "default_volgroup_id": 1,
    "enabled": "true",
    "default_bridge": "eth0",
    "network_security": "true",
    "cluster_id": 1,
    "id": 1
  }
}


-- Instance --
GET   /instances/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "instance": {
    "hostname": "test.dom.tld",
    "memory": 1024,
    "storage": 10,
    "image": "http://imagestore.virtualmaster.cz/images/1",
    "state": "running",
    "ipv4_addresses": 1,
    "ipv6_addresses": 1,
    "cores": 4,
    "hypervisor": "xen-paravirt",
    "cluster_id": 1,
    "tenant_id": 1,
    "hostnode_id": 1,
    "id": 1
  }
}


-- Ip --
GET   /ips/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "ip": {
    "ip": "10.0.0.2",
    "reverse": "2.0.0.10.in-addr.arpa.",
    "netmask": "255.255.255.0",
    "gateway": "10.0.0.1",
    "purpose": "infrastructure",
    "comment": "allocated for redundant gateway",
    "vif_id": 1,
    "subnet_id": 1,
    "state": "assigned",
    "version": 4,
    "id": 1
  }
}


-- Logvolumes --
GET   /logvolumes/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "logvolume": {
    "name": "test-dom-tld_root",
    "size": 10,
    "fstype": "ext3",
    "label": "root",
    "target": "xvda",
    "state": "ready",
    "snapshot_of_id": 1,
    "replication_resource_id": 1,
    "migration_id": 1,
    "meta_for_replication_resource_id": 1,
    "comment": "Do not run fsck!",
    "instance_id": 1,
    "volgroup_id": 1,
    "id": 1
  }
}


-- Migrations --
GET   /migrations/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "migration": {
    "instance_id": 1,
    "target_hostnode_id": 1,
    "source_hostnode_id": 2,
    "state": "ready",
    "id": 1
  }
}


-- Replication Resources --
GET   /replication_resources/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "replication_resource": {
    "minor": 221,
    "hostnode_id": 1,
    "replication_resource_id": 1,
    "id": 1
  }
}


-- Subnets --
GET   /subnets/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "migration": {
    "instance_id": 1,
    "target_hostnode_id": 1,
    "source_hostnode_id": 2,
    "state": "ready",
    "id": 1
  }
}


-- Vifs --
GET   /vifs/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "vif": {
    "name": "eth0",
    "mac": "00:00:00:00:00:00",
    "instance_id": 1,
    "id": 1
  }
}


-- Volgroups --
GET   /volgroups/1
> Accept: application/json
< 201
< Content-Type: application/json
{
  "volgroup": {
    "name": "node1_main",
    "comment": "On top of raid 1+0",
    "size": "1024",
    "hostnode_id": 1,
    "id": 1
  }
}

-- Issue --
Retreive record with history (chat, state changes, reassignements)
GET   /issues/1.json?include=journals
> Accept: application/json
< 201
< Content-Type: application/json
{
  "issue": {
    "created_on": "2012/09/16 14:53:42 +0200",
    "description": "Textual description in multiple lines \r\n http://www.redmine.org/projects/redmine/wiki/Rest_api",
    "status": {
      "name": "Resolved",
      "id": 3
    },
    "subject": "Update redmine.dev.vmin.cz to 1.4+",
    "spent_hours": 0.0,
    "author": {
      "name": "Adam Kliment",
      "id": 5
    },
    "assigned_to": {
      "name": "Adam Kliment",
      "id": 5
    },
    "done_ratio": 0,
    "tracker": {
      "name": "Feature",
      "id": 2
    },
    "start_date": "2012/09/16",
    "project": {
      "name": "Support issue tracker",
      "id": 65
    },
    "journals": [
      {
        "created_on": "2012/09/16 21:16:02 +0200",
        "notes": "Texttual comment\r\nin multiple lines",
        "details": [
          {
            "old_value": "1",
            "name": "status_id",
            "property": "attr",
            "new_value": "2"
          },
          {
            "old_value": "5",
            "name": "assigned_to_id",
            "property": "attr",
            "new_value": "4"
          }
        ],
        "user": {
          "name": "jan kaufman",
          "id": 4
        },
        "id": 845
      },
      {
        "created_on": "2012/09/17 00:25:14 +0200",
        "notes": "solved at #239\r\n",
        "details": [
          {
            "old_value": "2",
            "name": "status_id",
            "property": "attr",
            "new_value": "3"
          },
          {
            "old_value": "4",
            "name": "assigned_to_id",
            "property": "attr",
            "new_value": "5"
          }
        ],
        "user": {
          "name": "jan kaufman",
          "id": 4
        },
        "id": 859
      }
    ],
    "updated_on": "2012/09/17 00:25:14 +0200",
    "id": 469,
    "due_date": "2012/09/20",
    "fixed_version": {
      "name": "Dispatching",
      "id": 17
    },
    "priority": {
      "name": "High",
      "id": 5
    }
  }
}


Retreive all recodrs without journal
GET   /issues.json
> Accept: application/json
< 201
< Content-Type: application/json
{
  "limit": "25",
  "total_count": "2",
  "offset": "0",
  "issues": [
    {
      "created_on": "2012/09/16 14:53:42 +0200",
      "description": "Textual description in multiple lines \r\n http://www.redmine.org/projects/redmine/wiki/Rest_api",
      "status": {
        "name": "Resolved",
        "id": 3
      },
      "subject": "Update redmine.dev.vmin.cz to 1.4+",
      "spent_hours": 0.0,
      "author": {
        "name": "Adam Kliment",
        "id": 5
      },
      "assigned_to": {
        "name": "Adam Kliment",
        "id": 5
      },
      "done_ratio": 0,
      "tracker": {
        "name": "Feature",
        "id": 2
      },
      "start_date": "2012/09/16",
      "project": {
        "name": "Support issue tracker",
        "id": 65
      },
      "updated_on": "2012/09/17 00:25:14 +0200",
      "id": 469,
      "due_date": "2012/09/20",
      "fixed_version": {
        "name": "Dispatching",
        "id": 17
      },
      "priority": {
        "name": "High",
        "id": 5
      }
    },
    {
      "created_on": "2012/09/16 14:53:42 +0200",
      "description": "Textual description in multiple lines \r\n http://www.redmine.org/projects/redmine/wiki/Rest_api",
      "status": {
        "name": "Resolved",
        "id": 3
      },
      "subject": "Update redmine.dev.vmin.cz to 1.4+",
      "spent_hours": 0.0,
      "author": {
        "name": "Adam Kliment",
        "id": 5
      },
      "assigned_to": {
        "name": "Adam Kliment",
        "id": 5
      },
      "done_ratio": 0,
      "tracker": {
        "name": "Feature",
        "id": 2
      },
      "start_date": "2012/09/16",
      "project": {
        "name": "Support issue tracker",
        "id": 65
      },
      "updated_on": "2012/09/17 00:25:14 +0200",
      "id": 469,
      "due_date": "2012/09/20",
      "fixed_version": {
        "name": "Dispatching",
        "id": 17
      },
      "priority": {
        "name": "High",
        "id": 5
      }
    }
  ]
}


Create new Issue
POST /issue.json
> Accept: application/json
{
  "issue": {
    "project_id": "example",
    "subject": "Update redmine.dev.vmin.cz to 1.4+",
    "description": "Textual description in multiple lines \r\n http://www.redmine.org/projects/redmine/wiki/Rest_api"
  }
}
< 201
< Content-Type: application/json
{
  "issue": {
    "created_on": "2012/09/16 14:53:42 +0200",
    "description": "Textual description in multiple lines \r\n http://www.redmine.org/projects/redmine/wiki/Rest_api",
    "status": {
      "name": "Resolved",
      "id": 3
    },
    "subject": "Update redmine.dev.vmin.cz to 1.4+",
    "spent_hours": 0.0,
    "author": {
      "name": "Adam Kliment",
      "id": 5
    },
    "assigned_to": {
      "name": "Adam Kliment",
      "id": 5
    },
    "done_ratio": 0,
    "tracker": {
      "name": "Feature",
      "id": 2
    },
    "start_date": "2012/09/16",
    "project": {
      "name": "Support issue tracker",
      "id": 65
    },
    "updated_on": "2012/09/17 00:25:14 +0200",
    "id": 469,
    "due_date": "2012/09/20",
    "fixed_version": {
      "name": "Dispatching",
      "id": 17
    },
    "priority": {
      "name": "High",
      "id": 5
    }
  }
}


Update Issue
PUT /issue.json
> Accept: application/json
{
  "issue": {
    "subject": "Example issue (was: Test issue)",
    "notes": "Changing the subject"
  }
}
< 204



Delete Issue
DELETE /issue.json
> Accept: application/json
{
  "issue": {
    "subject": "Example issue (was: Test issue)",
    "notes": "Changing the subject"
  }
}
< 204





