-- Service invoice items --

Create new, not invoiced (opened) service invoice item for customer

Attributes:

  - desc: Item description
  - quantity: invoiced units queantity
  - unitprice: price for 1 invoiced unit without tax
  - discount: discount in percents
  - tax: tax in percents
  - note: Item note
  - code: Code for type of transaction
  - started_at: start of fullfillment in format ISO 8601
  - ended_at: end of fullfillment in format ISO 8601

POST /customers/1/service_invoice_items
> Accept: application/json
***** ServiceInvoiceItem.not_saved
< 201
< Content-Type: application/json
***** ServiceInvoiceItem.saved


Get all customer's invoice items
GET /customers/1/service_invoice_items
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInvoiceItem.saved


Get specific invoice item
GET /customers/1/service_invoice_items/1
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInvoiceItem.all_saved


Update specifc invoice item
PUT /customers/1/service_invoice_items/1
> Accept: application/json
{
  "desc" "Changed item description"    
}
< 204


Delete specifc invoice item
DELETE /customers/1/service_invoice_items/1
> Accept: application/json
< 204


