-- Customers --

Creates new customer

Request attributes: 

  - email: Company's billing email contact
  - legal_name: Official, full name of company
  - street: Official address street name
  - number: Official address building number
  - address2: Additional address line
  - city: Official address city
  - zip: Postal code
  - country: country code ISO 3166-1 alpha-2
  - invoice_name: Name of representative of company able to reecive billing documents
  - ic: Company identification number
  - vat: TAX number (VAT number) without country prefix
  - vat_prefix: TAX number country prefix
  - locale: ISO 639-1 code of language used in all documents and official communication
  
POST   /customers
> Accept: application/json
***** Customer.not_saved
< 201
< Content-Type: application/json
***** Customer.saved


Get list of all customers
GET /customers
> Accept: application/json
< 200
< Content-Type: application/json
***** Customer.all_saved


Get detail of specific customer
GET    /customers/1
> Accept: application/json
< 200
< Content-Type: application/json
***** Customer.saved


Update specific customer
PUT    /customers/1
> Accept: application/json
{
  "email": "adam.kliment@virtualmaster.cz",
  "legal_name": "Virtualmaster",
}
< 204


Delete specific customer
DELETE    /customers/1
> Accept: application/json
< 204


-- Service instances --

Create service instance

Only admin can do this

Attributes:

- identificator: unique identificator for the service instance, if not present, will be generated
- price: unit price without tax
- currency: currency (can't differ from customer at the moment)
- service_attributes: JSON with serialized service attribtues

POST /customers/1/service_instances
***** ServiceInstance.not_saved
< 201
< Content-Type: application/json
***** ServiceInstance.saved

Get all existing service instances for the customer

GET /customers/1/service_instances
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInstance.all_saved

Get detail of existing service instance

GET /customers/1/service_instances/1
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInstance.saved


Update existing service instance

PUT /customers/1/service_instances/1
> Accept: application/json
{
    "price": "2",
    "service_attributes": {
        "volume": "4"
    }
}
< 204


Delete existing service instance

DELETE /customers/1/service_instances/1
> Accept: application/json
< 204


-- Service invoice items --

Create new, not invoiced (opened) service invoice item for customer

Attributes:

  - desc: Item description
  - quantity: invoiced units queantity
  - unitprice: price for 1 invoiced unit without tax
  - discount: discount in percents
  - tax: tax in percents
  - note: Item note
  - code: Code for type of transaction
  - started_at: start of fullfillment in format ISO 8601
  - ended_at: end of fullfillment in format ISO 8601

POST /customers/1/service_invoice_items
> Accept: application/json
***** ServiceInvoiceItem.not_saved
< 201
< Content-Type: application/json
***** ServiceInvoiceItem.saved


Get all customer's invoice items
GET /customers/1/service_invoice_items
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInvoiceItem.saved


Get specific invoice item
GET /customers/1/service_invoice_items/1
> Accept: application/json
< 200
< Content-Type: application/json
***** ServiceInvoiceItem.all_saved


Update specifc invoice item
PUT /customers/1/service_invoice_items/1
> Accept: application/json
{
  "desc" "Changed item description"    
}
< 204


Delete specifc invoice item
DELETE /customers/1/service_invoice_items/1
> Accept: application/json
< 204


-- Invoices --

Get all customer's existing invoices

GET /customers/1/invoices
> Accept: application/json
< 200
< Content-Type: application/json
***** Invoice.all_saved


Get detail of specific customer's 

GET /customers/1/invoices/2012010001
> Accept: application/json
< 200
< Content-Type: application/json
***** Invoice.saved


Download specific customer's invoice in PDF
Test comment for apiary

GET /customers/1/invoices/2012010001.pdf
< 200
< Content-Type:application/pdf




