--- Virtualmaster public API---
---
# Structure of resources
## Infrastructure
Available at URL: https://infra.virtualmaster.com/api/v1/

Resouces:

- Virtual
- Ip Address
- Hostnode
- Cluster
- Network interface
- Migration
- Request
- Setting
- Subnet
- Violation
- Volume group
- Logical volume
- Replication

## Billing
Available at URL: https://billing.virtualmaster.com/api/v1/

Resources:

- Customer
- Service Instance
- Invoice
- Service Invoice Item
- Grouped Consumed Resources

## Support
Available at URL: https://support.virtualmaster.com/api/v1/

Resources:

- Issue
- Issue Item
- Tracked Time

## Imagestore
Available at URL: https://imagestore.virtualmaster.com/api/v1/

Resources:

- Image
- Operating System

## Backup
Available at URL: https://backup.virtualmaster.com/api/v1/

Resources:

- Repository
- Backup


## ID - OAuth provider
Available at URL: https://id.virtualmaster.com/api/v1/

Resources:

- Person
- Email
- Phone Number
- SSH Key
- Authorized Backend

---

