-- Authorized Backend --
Retreive all authorized backends for person
GET   /persons/1/authorized_backends
> Accept: application/json
< 201
< Content-Type: application/json
***** AuthorizedBackend.all




