
-- Cluster --
GET   /clusters/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Cluster.saved


-- Hostnode --
GET   /hostnodes/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Hostnode.saved


-- Instance --
GET   /instances/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Instance.saved


-- Ip --
GET   /ips/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Ip.saved


-- Logvolumes --
GET   /logvolumes/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Logvolume.saved


-- Migrations --
GET   /migrations/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Migration.saved


-- Replication Resources --
GET   /replication_resources/1
> Accept: application/json
< 201
< Content-Type: application/json
***** ReplicationResource.saved


-- Subnets --
GET   /subnets/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Migration.saved


-- Vifs --
GET   /vifs/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Vif.saved


-- Volgroups --
GET   /volgroups/1
> Accept: application/json
< 201
< Content-Type: application/json
***** Volgroup.saved

