-- Instance --

POST   /instances
> Accept: application/json
***** Instance.not_saved
< 201
< Content-Type: application/json
***** Instance.saved


GET   /instances
> Accept: application/json
< 201
< Content-Type: application/json
***** Instance.many_saved



